name: autotech
description: AutoTech - app de oficina mecânica no estilo Apple (Flutter + Cupertino)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.7.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  add_2_calendar: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/images/